public class WW_CovidRows {
    public String total_deaths{get;set;}
    public String new_cases{get;set;}
    public String new_deaths{get;set;}
    public String total_cases{get;set;}
    public String total_recovered{get;set;}
    public String country_abbreviation{get;set;}
    public String active_cases{get;set;}
    public String country{get;set;}
    public String serious_critical{get;set;}
    public String cases_per_mill_pop{get;set;}
    public String flag{get;set;}
}